apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignition-api
  namespace: ignition-system
  annotations:
    iam.gke.io/gcp-service-account: ignition-api@__ONBOARD_PROJECT__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignition-controller
  namespace: ignition-system
  annotations:
    iam.gke.io/gcp-service-account: ignition-controller@__ONBOARD_PROJECT__.iam.gserviceaccount.com
