apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ignition-api
  namespace: ignition-system
spec:
  domains:
    - api.ignition.dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ignition-api
  namespace: ignition-system
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ignition-api
    networking.gke.io/managed-certificates: ignition-api
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: api.ignition.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ignition-api
                port:
                  number: 8080
