apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignition-api
  namespace: ignition-system
  annotations:
    iam.gke.io/gcp-service-account: ignition-api@ignition-dev.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignition-controller
  namespace: ignition-system
  annotations:
    iam.gke.io/gcp-service-account: ignition-controller@ignition-dev.iam.gserviceaccount.com
